name: bombas-costarricenses

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: push      
        id: push
        uses: ./
        uses: actions/bombas-costarricenses-push@v1
