name: bombas-costarricenses

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: push
        uses: ./
        id: push
        with:
          user_name: ${{ secrets.USER_NAME }}
          user_email: ${{ secrets.USER_EMAIL }}
          cli_config: ${{ secrets.CLI_CONFIG }}
          skill_id: ${{ secrets.SKILL_ID }}
          profile: ${{ secrets.PROFILE }}
          skill_name: skill
